stages:
  - security

checkov_scan_manifests:
  stage: security
  image:
    name: alpine:latest
    entrypoint: [""]
  script:
    - apk add --no-cache python3 py3-pip jq
    - pip install checkov
    - echo "Running Checkov scan on Kubernetes manifests"
    - checkov -d . -o json > full_checkov_output.json
    - cat full_checkov_output.json | jq '.results.failed_checks[] | {check_id, check_name, file_path, resource, guideline}' > checkov_results.txt
  allow_failure: true
  artifacts:
    paths:
      - checkov_results.txt
      - full_checkov_output.json
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "operations"'
