stages:
  - security

checkov_scan_manifests:
  stage: security
  image:
    name: bridgecrew/checkov:3.2.436
    entrypoint: [""]
  variables:
    BC_SKIP_MAPPING: "true"  # Critical fix to skip authentication
    #BC_API_KEY: "skip"        # Backup solution
  script:
    -  echo "Installing Checkov and dependencies"
    - apt-get update && apt-get install -y jq
    - echo "Checkov version"
    - echo $(checkov --version)
    - echo "Running Checkov scan on Kubernetes manifests"
    - checkov -d . --skip-download --skip-results-upload --compact -o json > full_checkov_output.json
    - cat full_checkov_output.json | jq '.results.failed_checks[] | {check_id, check_name, file_path, resource, guideline}' > checkov_results.txt
  allow_failure: true
  artifacts:
    paths:
      - checkov_results.txt
      - full_checkov_output.json
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "operations"'
