#cloud-config
package_update: true
packages:
  - curl

users:
  - name: master
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    home: /home/master
    create_home: true
    ssh-authorized-keys:
      - "${ssh_public_key}"
      - "${worker_ssh_public_key}"

runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable-cloud-controller --kubelet-arg cloud-provider=external" sh -
  - chown master:master /etc/rancher/k3s/k3s.yaml
  - chown master:master /var/lib/rancher/k3s/server/node-token
