#cloud-config
packages:
  - curl
users:
  - name: worker
    ssh-authorized-keys:
      - ${var.ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

runcmd:
  - apt-get update -y
  - until curl -k https://10.0.1.1:6443; do sleep 5; done
  - REMOTE_TOKEN=$(ssh -o StrictHostKeyChecking=accept-new root@10.0.1.1 sudo cat /var/lib/rancher/k3s/server/node-token)
  - curl -sfL https://get.k3s.io | K3S_URL=https://10.0.1.1:6443 K3S_TOKEN=$REMOTE_TOKEN INSTALL_K3S_EXEC="--kubelet-arg cloud-provider=external" sh -