apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/barywhyte/private-pro.git
    targetRevision: operations
    path: operations/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

