apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: barywhyte/api
    argocd-image-updater.argoproj.io/barywhyte-api.update-strategy: latest
    argocd-image-updater.argoproj.io/barywhyte-api.pull-secret: registrycredentials
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: operations
spec:
  project: default

  source:
    repoURL: https://gitlab.com/barywhyte/private-pro.git
    #repoURL: https://github.com/barywhyte/private-project.git
    targetRevision: operations
    path: operations/api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

