apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-app-monitor
  namespace: monitoring   # Prometheus watches this namespace for ServiceMonitors
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - api
  endpoints:
    - port: http    # must match the port name in the Service
      path: /metrics
      interval: 15s
