apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
  namespace: {{ .Values.namespace }}
spec:
  metrics:
    - name: health-check
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result > 0.95
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring:9090
          query: |
            1 - (
              sum(rate(django_http_requests_total_by_view_transport_method_total{status=~"5.."}[1m]))
              /
              sum(rate(django_http_requests_total_by_view_transport_method_total[1m]))
            )
