apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
  namespace: {{ .Values.namespace }}
spec:
  metrics:
    - name: health-check
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result == true
      provider:
        web:
          #url: http://{{ .Chart.Name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.service.targetPort }}/health
          url: https://barywhyt.duckdns.org/health
          timeout: 10
