apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
  namespace: {{ .Values.namespace }}
spec:
  metrics:
    - name: health-check
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result == 200
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: check
                    image: curlimages/curl
                    command: ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://{{ .Chart.Name }}-preview/health"]

                restartPolicy: Never
        #prometheus:
        #  address: http://monitoring-kube-prometheus-prometheus.monitoring:9090
        #  query: |
        #     sum(rate(django_http_responses_total_by_status_total{status=~"5.."}[1m]))

            #(
            #  sum by () (rate(django_http_responses_total_by_status_total{status="200"}[1m]))
            #  /
            #  sum by () (rate(django_http_responses_total_by_status_total[5m]))
            #) * 100
