apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
  namespace: {{ .Values.namespace }}
spec:
  metrics:
    - name: health-check
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result[0] >= 90
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring:9090
          query: |
            (
              sum(rate(django_http_responses_total_by_status_total{service='api-preview', status='200'}[5m]))
              /
              sum(rate(django_http_responses_total_by_status_total{service='api-preview'}[5m]))
            ) * 100



        #job:
        #  spec:
        #    template:
        #      spec:
        #        containers:
        #          - name: check
        #            image: curlimages/curl
        #            command: ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://{{ .Chart.Name }}-preview/health"]

                restartPolicy: Never
