apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
  namespace: {{ .Values.namespace }}
spec:
  metrics:
    - name: health-check
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: result[0] > 90
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring:9090
          query: |
            (
              sum by () (rate(django_http_responses_total_by_status_total{status="200"}[5m]))
              /
              sum by () (rate(django_http_responses_total_by_status_total[5m]))
            ) * 100
