apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-binding
  namespace: {{ .Values.namespace }}
subjects:
{{- range .Values.namespaceDeveloper.users }}
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
roleRef:
  kind: Role
  name: api-dev
  apiGroup: rbac.authorization.k8s.io
