apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-dev
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
