apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-auditor-binding

subjects:
{{- range .Values.clusterAuditor.users }}
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
roleRef:
  kind: ClusterRole
  name: cluster-auditor
  apiGroup: rbac.authorization.k8s.io
