apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-auditor
rules:
  - apiGroups: [""]               # core API group
    resources:
      - nodes
      - pods
      - services
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - endpoints
      - replicationcontrollers
      - events
      - namespaces
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps", "extensions"]  # workload-related groups
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]          # batch jobs
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]  # RBAC resources
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]

