apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-auditor
rules:
  - apiGroups: ["", "apps", "extensions", "batch"]
    resources: ["nodes", "pods", "deployments", "services", "configmaps", "replicasets", "jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: []
