apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 120
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for database..."
              until nc -z $DATABASE_HOST $DATABASE_PORT; do
                echo "DB is not ready, sleeping..."
                sleep 3
              done
              echo "DB is ready, running migrations..."
              python manage.py migrate --settings=app.settings.prod
          env:
            - name: DATABASE_HOST
              value: {{ .Values.db.host }}
            - name: DATABASE_PORT
              value: "{{ .Values.db.port }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretname }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretname }}
                  key: POSTGRES_PASSWORD

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DATABASE_HOST
              value: {{ .Values.db.host }}
            - name: DATABASE_PORT
              value: "{{ .Values.db.port }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretname }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretname }}
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"

  strategy:
    blueGreen:
      activeService: {{ .Chart.Name }}
      previewService: {{ .Chart.Name }}-preview
      autoPromotionEnabled: true
      #scaleDownDelayRevisionLimit: 2  # Keep last 2 revisions for rollback


      # Add both pre and post promotion analysis
      #prePromotionAnalysis:
      #  templates:
      #    - templateName: health-check-analysis
      postPromotionAnalysis:  # REQUIRED for rollback after traffic switch
        templates:
          - templateName: health-check-analysis
