apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-abort-controller
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-abort-controller
  template:
    metadata:
      labels:
        app: rollout-abort-controller
    spec:
      serviceAccountName: rollout-controller
      containers:
        - name: controller
          image: barywhyte/rollout-abort-controller:latest
          env:
            - name: NAMESPACE
              value: "api"
          command: ["/bin/sh", "-c", "while true; do /watch-rollout.sh; sleep 30; done"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-controller
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: rollout-controller-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-controller-rolebinding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rollout-controller-role
subjects:
  - kind: ServiceAccount
    name: rollout-controller
    namespace: api
