fullnameOverride: api
namespace: api
replicaCount: 2
image:
  repository: docker.io/barywhyte/api
  tag: ""
imagePullSecret: registrycredentials
containerPort: 8000
readinessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
livenessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 5
  httpHeaders:
    - name: Host
      value: barywhyt.duckdns.org
service:
  port: 80
  targetPort: 8000
  name: http
  type: ClusterIP
ingress:
  clusterIssuer: letsencrypt-prod
  class: nginx
  forceSSLRedirect: "true"
  host: barywhyt.duckdns.org
  tlsSecret: barywhyt-tls
  paths:
    - path: /health
      port: 80
    - path: /info
      port: 80
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
serviceMonitor:
  enabled: true
  namespace: monitoring
  targetNamespace: api
  release: monitoring
  port: http
  path: /metrics
  interval: 15s
  selectorLabels:
    app: api
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
namespaceDeveloper:
  users:
    - dev-user
    - tester
clusterAuditor:
  users:
    - audit-user1
    - audit-user2
networkPolicy:
  enabled: true
db:
  secretname: postgres-secret
  host: db-postgresql.db.svc.cluster.local
  port: 5432
