namespace: api
replicaCount: 3

image:
  repository: barywhyte/api
  tag: v2

imagePullSecret: registrycredentials
containerPort: 8000

service:
  port: 80
  targetPort: 8000
  type: ClusterIP

ingress:
  clusterIssuer: letsencrypt-prod
  class: nginx
  forceSSLRedirect: "true"
  host: barywhyt.duckdns.org
  tlsSecret: barywhyt-tls
  paths:
    - path: /health
      port: 80
    - path: /info
      port: 80

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
