apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/barywhyte/private-pro.git
    targetRevision: operations
    path: operations/helms  # <--- This folder has Helm chart or plain YAMLs with child apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
