# Generated by Django 5.2.4 on 2025-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Api",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("contents", models.TextField(max_length=500)),
                ("author", models.CharField(default="Anonymous", max_length=50)),
            ],
        ),
    ]
