# Generated by Django 5.2.4 on 2025-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="title",
            field=models.CharField(),
        ),
    ]
