# Generated by Django 5.2.4 on 2025-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_api_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="api",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
