# Generated by Django 5.2.4 on 2025-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_api_price_alter_api_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
