# Generated by Django 5.2.4 on 2025-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_api_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="featured",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
