# Generated by Django 5.2.4 on 2025-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_api_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
