# Generated by Django 5.2.4 on 2025-08-12 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_api_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="featured",
        ),
        migrations.AddField(
            model_name="api",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
